const tasks = [
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/bootstrap.jpg",
    title: "Argon Design System",
    responsibleTeam: "Developer",
    status: "pending",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 60,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Angular Now UI Kit PRO",
    responsibleTeam: "Analist",
    status: "completion",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/angular.jpg",
    title: "Black Dashboard Sketch",
    responsibleTeam: "UX/UI",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "medium",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 73,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/react.jpg",
    title: "React Material Dashboard",
    responsibleTeam: "Developer",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "low",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: true,
    completion: 90,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
  {
    taskImg: "https://demos.creative-tim.com/notus-js/assets/img/vue.jpg",
    title: "Vue Material Dashboard ",
    responsibleTeam: "Analyst",
    status: "delayed",
    assignedTo: [
      "https://demos.creative-tim.com/notus-js/assets/img/team-1-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-3-800x800.jpg",
      "https://demos.creative-tim.com/notus-js/assets/img/team-4-470x470.png",
    ],
    priority: "High",
    dueDate: new Date(Date.now()).toLocaleDateString(),
    del_flg: false,
    completion: 100,
  },
];

export default tasks;
