import {
  INotification,
  NotificationChannel,
  NotificationResourceType,
  NotificationStatus,
  NotificationType,
} from "./notificationInterface";

const dummyNotifications: INotification[] = [
  {
    notificationId: "notif_001",
    recipientId: ["user_001"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskUpdated,
    title: "Task Updated",
    message: "The task 'Fix Login Issue' has been updated.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_101",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Fix Login Issue", updatedBy: "Alice" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_002",
    recipientId: ["user_002"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskCompleted,
    title: "Task Completed",
    message: "The task 'Write API Documentation' has been completed.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_102",
    status: NotificationStatus.Read,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Write API Documentation", completedBy: "Bob" },
    createdAt: new Date(),
    readAt: new Date(),
    isRead: true,
  },
  {
    notificationId: "notif_003",
    recipientId: ["user_003"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskReassigned,
    title: "Task Reassigned",
    message: "The task 'Design Homepage UI' has been reassigned to you.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_103",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Design Homepage UI", reassignedBy: "Charlie" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_004",
    recipientId: ["user_004"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskDeleted,
    title: "Task Deleted",
    message: "The task 'Optimize Database Queries' has been deleted.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_104",
    status: NotificationStatus.Read,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Optimize Database Queries", deletedBy: "David" },
    createdAt: new Date(),
    readAt: new Date(),
    isRead: true,
  },
  {
    notificationId: "notif_005",
    recipientId: ["user_005"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskCreated,
    title: "New Task Assigned",
    message: "A new task 'Create Test Cases' has been assigned to you.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_105",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Create Test Cases", assignedBy: "Eve" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_006",
    recipientId: ["user_006"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskDeadlineApproaching,
    title: "Task Deadline Approaching",
    message: "The deadline for 'Deploy Feature X' is approaching.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_106",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Deploy Feature X", deadline: "Tomorrow" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_007",
    recipientId: ["user_007"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskStatusUpdated,
    title: "Task Status Updated",
    message: "The task 'Fix Payment Bug' status changed to 'In Progress'.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_107",
    status: NotificationStatus.Read,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Fix Payment Bug", newStatus: "In Progress" },
    createdAt: new Date(),
    readAt: new Date(),
    isRead: true,
  },
  {
    notificationId: "notif_008",
    recipientId: ["user_008"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskDueDateUpdated,
    title: "Task Due Date Changed",
    message: "The due date for 'Review Code Changes' has been updated.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_108",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Review Code Changes", newDueDate: "March 5" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_009",
    recipientId: ["user_009"],
    senderId: ["AFOP00027"],
    type: NotificationType.TaskAssignedToTeam,
    title: "Task Assigned to Your Team",
    message: "A new task 'Setup CI/CD Pipeline' has been assigned to your team.",
    resourceType: NotificationResourceType.Task,
    resourceId: "task_109",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { taskName: "Setup CI/CD Pipeline", team: "DevOps" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_010",
    recipientId: ["user_010"],
    senderId: ["AFOP00027"],
    type: NotificationType.SubtaskCreated,
    title: "Subtask Created",
    message: "A subtask 'Write Unit Tests' has been created for your task.",
    resourceType: NotificationResourceType.Subtask,
    resourceId: "subtask_201",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { subtaskName: "Write Unit Tests", parentTask: "Refactor Code" },
    createdAt: new Date(),
    isRead: false,
  },
  {
    notificationId: "notif_011",
    recipientId: ["user_011"],
    senderId: ["AFOP00027"],
    type: NotificationType.SubtaskCompleted,
    title: "Subtask Completed",
    message: "The subtask 'Update README' has been completed.",
    resourceType: NotificationResourceType.Subtask,
    resourceId: "subtask_202",
    status: NotificationStatus.Read,
    channel: NotificationChannel.InApp,
    metaData: { subtaskName: "Update README", completedBy: "Mike" },
    createdAt: new Date(),
    readAt: new Date(),
    isRead: true,
  },
  {
    notificationId: "notif_012",
    recipientId: ["user_012"],
    senderId: ["AFOP00027"],
    type: NotificationType.SubtaskDeadlineApproaching,
    title: "Subtask Deadline Approaching",
    message: "The deadline for 'Write Integration Tests' is tomorrow.",
    resourceType: NotificationResourceType.Subtask,
    resourceId: "subtask_203",
    status: NotificationStatus.Unread,
    channel: NotificationChannel.InApp,
    metaData: { subtaskName: "Write Integration Tests", deadline: "Tomorrow" },
    createdAt: new Date(),
    isRead: false,
  },
  // Add 8 more notifications in a similar format...
];

// Exporting if needed
export default dummyNotifications;
