export const users = [
  {
    fullName: "John Michael",
    profilePic: "",
    email: "john@gmail.com",
    role: "Manager",
    team: "Organisation",
    status: "active",
    joined: "23/04/18",
  },
  {
    fullName: "Alexa Liras",
    profilePic: "",
    email: "alexa@gmail.com",
    role: "Member",
    team: "Developer",
    status: "inactive",
    joined: "11/01/19",
  },
  {
    fullName: "Laurent Perrier",
    profilePic: "",
    email: "laurent@gmail.com",
    role: "Member",
    team: "Projects",
    status: "suspended",
    joined: "19/09/17",
  },
  {
    fullName: "Michael Levi",
    profilePic: "",
    email: "Michael@gmail.com",
    role: "Member",
    team: "Developer",
    status: "active",
    joined: "24/12/08",
  },
  {
    fullName: "Richard Gran",
    profilePic: "",
    email: "richard@gmail.com",
    role: "Manager",
    team: "Executive",
    status: "inactive",
    joined: "04/10/21",
  },
  {
    fullName: "Miriam Eric",
    profilePic: "",
    email: "miriam@gmail.com",
    role: "Memeber",
    team: "Developer",
    status: "suspended",
    joined: "04/10/21",
  },
  {
    fullName: "John Michael",
    profilePic: "",
    email: "john@gmail.com",
    role: "Manager",
    team: "Organisation",
    status: "active",
    joined: "23/04/18",
  },
  {
    fullName: "Alexa Liras",
    profilePic: "",
    email: "alexa@gmail.com",
    role: "Member",
    team: "Developer",
    status: "inactive",
    joined: "11/01/19",
  },
  {
    fullName: "Laurent Perrier",
    profilePic: "",
    email: "laurent@gmail.com",
    role: "Member",
    team: "Projects",
    status: "suspended",
    joined: "19/09/17",
  },
  {
    fullName: "Michael Levi",
    profilePic: "",
    email: "Michael@gmail.com",
    role: "Member",
    team: "Developer",
    status: "active",
    joined: "24/12/08",
  },
  {
    fullName: "Richard Gran",
    profilePic: "",
    email: "richard@gmail.com",
    role: "Manager",
    team: "Executive",
    status: "inactive",
    joined: "04/10/21",
  },
  {
    fullName: "Miriam Eric",
    profilePic: "",
    email: "miriam@gmail.com",
    role: "Memeber",
    team: "Developer",
    status: "suspended",
    joined: "04/10/21",
  },
  {
    fullName: "John Michael",
    profilePic: "",
    email: "john@gmail.com",
    role: "Manager",
    team: "Organisation",
    status: "active",
    joined: "23/04/18",
  },
  {
    fullName: "Alexa Liras",
    profilePic: "",
    email: "alexa@gmail.com",
    role: "Member",
    team: "Developer",
    status: "inactive",
    joined: "11/01/19",
  },
  {
    fullName: "Laurent Perrier",
    profilePic: "",
    email: "laurent@gmail.com",
    role: "Member",
    team: "Projects",
    status: "suspended",
    joined: "19/09/17",
  },
  {
    fullName: "Michael Levi",
    profilePic: "",
    email: "Michael@gmail.com",
    role: "Member",
    team: "Developer",
    status: "active",
    joined: "24/12/08",
  },
  {
    fullName: "Richard Gran",
    profilePic: "",
    email: "richard@gmail.com",
    role: "Manager",
    team: "Executive",
    status: "inactive",
    joined: "04/10/21",
  },
  {
    fullName: "Miriam Eric",
    profilePic: "",
    email: "miriam@gmail.com",
    role: "Memeber",
    team: "Developer",
    status: "suspended",
    joined: "04/10/21",
  },
  {
    fullName: "John Michael",
    profilePic: "",
    email: "john@gmail.com",
    role: "Manager",
    team: "Organisation",
    status: "active",
    joined: "23/04/18",
  },
  {
    fullName: "Alexa Liras",
    profilePic: "",
    email: "alexa@gmail.com",
    role: "Member",
    team: "Developer",
    status: "inactive",
    joined: "11/01/19",
  },
  {
    fullName: "Laurent Perrier",
    profilePic: "",
    email: "laurent@gmail.com",
    role: "Member",
    team: "Projects",
    status: "suspended",
    joined: "19/09/17",
  },
  {
    fullName: "Michael Levi",
    profilePic: "",
    email: "Michael@gmail.com",
    role: "Member",
    team: "Developer",
    status: "active",
    joined: "24/12/08",
  },
  {
    fullName: "Richard Gran",
    profilePic: "",
    email: "richard@gmail.com",
    role: "Manager",
    team: "Executive",
    status: "inactive",
    joined: "04/10/21",
  },
  {
    fullName: "Miriam Eric",
    profilePic: "",
    email: "miriam@gmail.com",
    role: "Memeber",
    team: "Developer",
    status: "suspended",
    joined: "04/10/21",
  },
];
